sm.route.watch({
    "^\s*$":function(){
       sm.view.makeui("noname",["view/pages/index.html"]); 
    },
    "#index.html":function(){
        console.log("why!!!!!!!!!!!!!!!");
       sm.view.makeui("noname",["view/pages/index.html"]); 
    },
    "#login.html":function(){
       sm.view.makeui("noname",["view/pages/login.html"]);
    },
    "^\#?$":function(hash){
       sm.route.to("#manage/home.html");
    },
    "^\#(manage\/(home|member|product|order|marketing|shop|finance|picture|mkt_lunbo|mkt_home)\.html)$":function(hash){
        sm.user.checkright(801).success(function(){
           var path;
            hash.replace(/^\#(.*\.html)$/,function(t,v){path=v;});
            sm.view.setvar("layout.curpath",path.split("/"),"common");
            path="view/pages/"+path;
            sm.view.makeui("hadmin",["view/parts/sidebar.hadmin.html@left","view/parts/toolbar.hadmin.html@toolbar",path+"@page"]);
            
       }).error(function(){
           sm.route.to("#login.html");
       });
    },
    "#test.html":function(){
         sm.view.makeui("noname",["test.html"]);
    },
    "#db.html":function(){
         sm.view.makeui("noname",["db.html"]);
    },
    "#json.html":function(){
         sm.view.makeui("noname",["json.html"]);
    },
    "(.*)":function(hash){
       document.body.innerText="404";
    },
});
console.log("router.js加载完成！");
